export const GET_DAILY_PLANS = "GET_DAILY_PLANS";
export const RECENTLY_PLAYED_AUDIOS = "RECENTLY_PLAYED_AUDIOS";

export const SET_SUBSCRIBED_USER = "SET_SUBSCRIBED_USER";
export const IS_USER_SUBSCRIBED = "IS_USER_SUBSCRIBED";
export const SET_OFFERS = "SET_OFFERS";
export const SET_PROMO_CODE_APPLIED = "SET_PROMO_CODE_APPLIED";
export const IS_FIRST_FREE_AUDIO_PLAY = "IS_FIRST_FREE_AUDIO_PLAY";
