-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4GwTTNgOtamEEF9s
U1Lbe/iiXzm+UwsuD2XBouO/26CgCgYIKoZIzj0DAQehRANCAASdiPKMc3P3cfuk
xwFQKQysDYRN5x0DU2DnWSInuC6Ehvxb9UB2Loh/VzzKc4mvAK5gyNfm7Cy0xoq/
zgMRHVMc
-----END PRIVATE KEY-----