import RatingIcon from "../../assets/icons/rating-icon.svg";
import { Backgrounds } from "../../data/background";
import { scaleSize } from "../../styles/mixins";
import { font } from "../../styles/theme";
import i18n from "../../translations/i18n";
import ZoulSubscribe from "../why-zoul/ZoulSubscribe";

export const slides = [
  // ZOUL INTRO SLIDES
  {
    title: { text: "What Zoul Is", textSize: 26 },
    text1: {
      text: "Zoul is a revolutionary meditation",
      margin: [scaleSize(28), 0, 0, 0],
      textSize: 22,
    },
    text2: {
      text: "Zoul offers a rare",
      margin: [scaleSize(28), 0, 0, 0],
      textSize: 22,
    },
    text3: {
      text: "Available in 17 languages",
      margin: [scaleSize(28), 0, 0, 0],
      textSize: 22,
    },
    padding: { paddingLeft: 40, paddingRight: 24 },
    image: Backgrounds.p3BgSlide1,
    sectionType: "zoulIntro",
  },
  {
    title: {
      text: "Zoul’s Uniqueness",
      textSize: 24,
    },
    bulletTextSize: 21,
    bulletPoints: [
      {
        id: 1,
        text: "Awakening",
      },
      {
        id: 2,
        text: "Authentic",
      },
      {
        id: 3,
        text: "Thinkers",
      },
      {
        id: 4,
        text: "Personalized",
      },
      {
        id: 5,
        text: "Ancient Wisdom Meets",
      },
      {
        id: 6,
        text: "Affordability",
      },
      {
        id: 7,
        text: "Life Companion:",
      },
    ],
    image: Backgrounds.p3BgSlide2,
    bulletMargin: [0, 0, 0, scaleSize(10)],
    bulletBlockMargin: [scaleSize(28), 0, 0, 0],
    isBullet: true,
    padding: { paddingRight: 40, paddingLeft: 40 },
    sectionType: "zoulIntro",
  },
  {
    title: {
      text: "Creators behind Zoul",
      textSize: 24,
    },
    text1: {
      textSize: 22,
      text: "We, the team behind Zoul,",
      margin: [scaleSize(28), 0, 0, 0],
    },
    text2: {
      textSize: 22,
      text: "To us,",
      margin: [scaleSize(28), 0, 0, 0],
    },
    image: Backgrounds.p3BgSlide3,
    sectionType: "zoulIntro",
    padding: { paddingRight: 40, paddingLeft: 40 },
  },
  {
    title: {
      text: "Empty Header Title",
      textSize: 24,
    },
    text1: {
      textSize: 22,
      text: "We crafted Zoul",
      margin: [scaleSize(22), 0, 0, 0],
    },
    text2: {
      textSize: 22,
      text: "We can’t wait to meet you",
      margin: [scaleSize(22), 0, 0, 0],
      isSemiBold: true,
    },
    image: Backgrounds.p3BgSlide3,
    sectionType: "zoulIntro",
    padding: { paddingRight: 40, paddingLeft: 40 },
  },
  {
    title: {
      text: "Empty Header Title",
      textSize: 24,
    },
    text1: {
      textSize: 22,
      text: "Thousands",
      margin: [scaleSize(22), 0, 0, 0],
    },
    text2: {
      textSize: 22,
      text: "These teachings",
      margin: [scaleSize(22), 0, 0, 0],
      isSemiBold: true,
    },
    text3: {
      textSize: 22,
      text: "Be liberated ",
      margin: [scaleSize(22), 0, 0, 0],
      isSemiBold: true,
    },
    image: Backgrounds.p3BgSlide3,
    sectionType: "zoulIntro",
    padding: { paddingRight: 24, paddingLeft: 40 },
  },
  // {
  //   title: { text: "Why We Care", textSize: 24 },
  //   text1: {
  //     textSize: 20,
  //     text: "Zoul is more than an app",
  //     margin: [scaleSize(28), 0, 0, 0],
  //   },
  //   text2: {
  //     textSize: 20,
  //     margin: [scaleSize(28), 0, 0, 0],
  //     text: "Passing on the wisdom",
  //   },
  //   text3: {
  //     textSize: 20,
  //     margin: [scaleSize(28), 0, 0, 0],
  //     text: "hear your life story",
  //   },
  //   padding: { paddingLeft: 40, paddingRight: 34 },
  //   image: Backgrounds.p3BgSlide4,
  //   sectionType: "zoulIntro",
  // },
  // {
  //   title: { text: "Zoul Unique Proposition", textSize: 24 },
  //   bulletPoints: [
  //     {
  //       id: 1,
  //       text: "Awakening activity",
  //     },
  //     {
  //       id: 2,
  //       text: "Authentic Content",
  //     },
  //     {
  //       id: 3,
  //       text: "Thinkers' Favorite",
  //     },
  //     {
  //       id: 4,
  //       text: "Personalized Daily Horoscope",
  //     },
  //     {
  //       id: 5,
  //       text: "Ancient Wisdom Meets Brain Science",
  //     },
  //     {
  //       id: 6,
  //       text: "Proven Result",
  //     },
  //     {
  //       id: 7,
  //       text: "Affordability Super",
  //     },
  //     {
  //       id: 8,
  //       text: "Life Companion",
  //     },
  //   ],
  //   image: Backgrounds.p3BgSlide5,
  //   bulletMargin: [0, scaleSize(10), scaleSize(4), scaleSize(10)],
  //   bulletBlockMargin: [scaleSize(28), 0, 0, 0],
  //   isBullet: true,
  //   bulletTextSize: 18,
  //   padding: { paddingLeft: 40, paddingRight: 34 },
  //   sectionType: "zoulIntro",
  // },
  // TESTIMONIAL SLIDES
  // {
  //   text: "I was thrilled",
  //   subText: "Hollywood actor",
  //   image: Backgrounds.p2BgSlide1,
  //   sectionType: "testimonial",
  //   textPaddingRight: 22,
  //   textPaddingLeft: 45,
  //   textPaddingBottom: 47,
  //   gap: 23,
  // },
  {
    text: "Discovering Zoul",
    subText: "Amela Kalari",
    image: Backgrounds.p2BgSlide1,
    sectionType: "testimonial",
    textPaddingRight: 22,
    textPaddingLeft: 45,
    textPaddingBottom: 47,
    gap: 23,
  },
  {
    text: "Zoul offers authentic",
    subText: "Medhat Nehad Seada",
    image: Backgrounds.p2BgSlide2,
    sectionType: "testimonial",
    textPaddingRight: 22,
    textPaddingLeft: 45,
    subTextSize: 18,
    subTextFontFamily: font.regular,
    textPaddingBottom: 47,
    gap: 23,
  },
  {
    text: "soul-awakening app",
    subText: "Judy chai",
    image: Backgrounds.p2BgSlide3,
    sectionType: "testimonial",
    textPaddingRight: 22,
    textPaddingLeft: 45,
    textSize: 19,
    textPaddingBottom: 50,
    gap: 21,
    subTextFontFamily: font.regular,
  },
  {
    text: "I was an alcoholic",
    subText: "Startup CEO",
    image: Backgrounds.p2BgSlide4,
    sectionType: "testimonial",
    icon: <RatingIcon />,
    subTextSize: 18,
    subTextFontFamily: font.regular,
    textPaddingRight: 30,
    textPaddingLeft: 45,
    textPaddingBottom: 49,
    gap: 21,
  },
  {
    text: "deep agony, watching",
    textSize: 19,
    subTextSize: 18,
    subTextFontFamily: font.regular,
    subText: "Park Engineer",
    image: Backgrounds.p2BgSlide5,
    sectionType: "testimonial",
    textPaddingRight: 20,
    textPaddingLeft: 43,
    textPaddingBottom: 58,
    gap: 15,
  },
  {
    text: "Zoul transformed my life",
    subText: "Dr Catherine",
    image: Backgrounds.p2BgSlide6,
    sectionType: "testimonial",
    subTextSize: 18,
    textPaddingRight: 21,
    textPaddingLeft: 41,
    textPaddingBottom: 46,
    gap: 14,
  },
  {
    text: "old meditation app—too repetitive",
    subText: "Sutha J",
    subTextSize: 18,
    subTextFontFamily: font.regular,
    image: Backgrounds.p2BgSlide7,
    sectionType: "testimonial",
    textPaddingRight: 22,
    textPaddingLeft: 40,
    textPaddingBottom: 45,
    gap: 12,
  },
  {
    text: "had a deep peaceful",
    subText: "Fahad I",
    image: Backgrounds.p2BgSlide8,
    subTextSize: 18,
    subTextFontFamily: font.regular,
    icon: <RatingIcon />,
    sectionType: "testimonial",
    textPaddingRight: 22,
    textPaddingLeft: 45,
    textPaddingBottom: 46,
    gap: 18,
  },
  {
    text: "Zoul washed away",
    subText: "Aisha M",
    image: Backgrounds.p2BgSlide9,
    subTextSize: 18,
    subTextFontFamily: font.regular,
    sectionType: "testimonial",
    icon: <RatingIcon />,
    textPaddingRight: 24,
    textPaddingLeft: 43,
    textPaddingBottom: 47,
    gap: 17,
  },
  //  ZOUL SUBSCRIBE SLIDE
  // {
  //   ZoulSubscribe: ZoulSubscribe,
  //   sectionType: "zoulSubscribe",
  // },
];
